language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install psycopg2
  # for python 2.7
  - pip install psycopg2-binary
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - export DB_TEST_URL="postgresql:///?host=localhost&dbname=travis_ci_test"
  - pytest test.py